---
title: "Summary Paper: Evaluating Asteroid Characteristics and Predicting Hazard Levels Using NASA's Asteroid Classification Dataset"
author: "Vishal Bakshi, Pratiksha Dange, Sudanshu Dotel, Qibin Huang"
date: "`r Sys.Date()`"
output: 
  prettydoc::html_pretty:
    theme: cayman
    toc: yes
---

## 1. Abstract 

<span style="font-size: 20px;  text-align: justify;">
Near-Earth objects (NEOs) such as asteroids pose a potential threat to Earth. Accurately assessing and classifying these threats is critical for developing effective mitigation strategies. This project utilizes NASA's Asteroid Classification dataset from Kaggle, which contains information on over 4,000 NEOs. Through exploratory data analysis and supervised machine learning approaches, we aim to gain insights into the key physical and orbital characteristics that distinguish potentially hazardous from non-hazardous asteroids. The models developed can contribute towards early warning systems to help categorize newly discovered celestial objects based on level of risk. Techniques to handle class imbalance will also be explored to improve model performance.
</span>

## 2. Introduction
<span style="font-size: 20px;  text-align: justify;">
Asteroids that pass close to Earth's orbit are called Near-Earth Objects (NEOs). A subset of NEOs classified as potentially hazardous asteroids (PHAs) pose a more significant risk due to their size and trajectory. NASA currently tracks over 25,000 NEOs and has categorized over 2,000 as PHAs [1]. Early and accurate classification of the threat level of discovered asteroids can provide precious lead time for mounting mitigation missions [2].
<P>
<P>This project utilizes a dataset from NASA containing information on over 4,000 NEOs, with the goal of developing machine learning models to effectively distinguish hazardous from non-hazardous asteroids. The dataset includes characteristics such as estimated diameter, relative velocity, orbital parameters and spectral types. Through exploratory data analysis, we will identify trends and correlations between these features and an asteroid's threat classification. Classification models such as random forests and neural networks will then be trained on this dataset to categorize asteroids as hazardous or non-hazardous. Techniques such as synthetic minority oversampling will also be employed to handle the class imbalance in the rare PHA category.
<P>The models produced from this project can help automatically classify future discovered NEOs to prioritize follow-up tracking and inform mitigation strategies. This has the potential to enhance asteroid impact prevention initiatives and reduce risks to our planet.
</span>

## 3. Motivation

<span style="font-size: 20px;  text-align: justify;">
Asteroid impact threats have captured public imagination and concern, especially following recent close calls. Most notably, the 340-meter asteroid 99942 Apophis caused alarm when initial observations indicated it had a 2.7% chance of hitting Earth in 2029. While later observations ruled out an impact, it will pass within 31,000 km of Earth’s surface – closer than some satellites [3].  
<P>
<P>This 2029 close encounter highlights the need for robust asteroid tracking and risk modeling systems. The surprise surrounding Apophis and its changing impact probabilities demonstrates gaps in our current classification approaches. The minor planet designation of asteroids also does not adequately communicate risk levels to the public. These limitations motivate the need for more accurate models that can rapidly incorporate new asteroid observations and provide clear warnings on potential hazards.
<P>
<P>Automated classification via machine learning provides a scalable way to screen discovered Near Earth Objects (NEOs) and identify priority threats for further tracking. With thousands of new NEOs found each year, manual threat assessment is infeasible [1]. Our project aims to develop machine learning models using NASA’s asteroid dataset that can reliably evaluate risks based on asteroid properties. Coupling these models with early warning infrastructure can enable rapid response to future threats. The capability to accurately classify asteroids will be crucial for preparation against the next Apophis-like object that comes too close for comfort. With continued asteroid mining and exploration, these classification systems will also inform policy and risk management strategies.
</span>

## 4. Dataset 
<span style="font-size: 20px;  text-align: justify;">
<p>Our dataset is available as [Nasa Asteroids Classification](https://www.kaggle.com/datasets/shrutimehta/nasa-asteroids-classification) at Kaggle. All the data is from the (http://neo.jpl.nasa.gov/). This API is maintained by Space Rocks Team: David Greenfield, Arezu Sarvestani, Jason English, and Peter Baunach. The dataset consists of 4687 data instances(rows) and 40 features(columns). Also, there are no null values in the dataset.
<P>
<p>Features’ description is given below;
</span>


<div class="column-definitions">
  <p><strong>1. Neo Reference ID:</strong> ID for the Asteroid</p>
  <p><strong>2. Name:</strong> Name of the Asteroid</p>
  <p><strong>3. Absolute Magnitude:</strong> Indicates the brightness of the asteroid; lower magnitude means a brighter star, higher magnitude means a dimmer star.</p>
  <p><strong>4. Est Dia in KM (min):</strong> Estimated minimum size of the asteroid in kilometers.</p>
  <p><strong>5. Est Dia in KM (max):</strong> Estimated maximum size of the asteroid in kilometers.</p>
  <p><strong>6. Close Approach Date:</strong> Date when the asteroid came very close to Earth's atmosphere.</p>
  <p><strong>7. Epoch Date Close Approach:</strong> A related date concerning the asteroid's close approach.</p>
  <p><strong>8. Relative Velocity (km per sec):</strong> The velocity of the asteroid.</p>
  <p><strong>9. Miss Dist. (Astronomical):</strong> The asteroid's closest approach to Earth, measured in astronomical units.</p>
  <p><strong>10. Miss Dist. (lunar):</strong> The distance in terms of the Moon's distance from Earth.</p>
  <p><strong>11. Miss Dist. (kilometers):</strong> The closest approach of the asteroid to Earth in kilometers.</p>
  <p><strong>12. Miss Dist. (miles):</strong> The closest approach in miles.</p>
  <p><strong>13. Orbiting Body:</strong> Indicates the celestial body that the asteroid orbits.</p>
  <p><strong>14. Orbit ID:</strong> An ID for the asteroid's orbit.</p>
  <p><strong>15. Orbit Determination Date:</strong> The date when the asteroid's orbit was calculated.</p>
  <p><strong>16. Orbit Uncertainty Minimum:</strong> A measure of the uncertainty in the asteroid's orbit.</p>
  <p><strong>17. Orbit Intersection:</strong> Indicates where the asteroid's orbit crosses.</p>
  <p><strong>18. Jupiter Tisserand Invariant:</strong> The JTI measures the influence of Jupiter's gravitational pull on celestial bodies; lower JTI values are farther from Jupiter.</p>
  <p><strong>19. Epoch Osculation:</strong> A specific date related to the asteroid.</p>
  <p><strong>20. Eccentricity:</strong> Determines the shape of the orbit; 0 < E < 1 indicates an ellipse, E = 1 is a parabola, and E > 1 is a hyperbola.</p>
  <p><strong>21. Semi Major Axis:</strong> Indicates the size of the asteroid's orbit.</p>
  <p><strong>22. Inclination:</strong> Denotes the tilt of the asteroid's orbit.</p>
  <p><strong>23. Asc Node Longitude:</strong> Specifies where the asteroid's orbit crosses a reference plane.</p>
  <p><strong>24. Orbital Period:</strong> Specifies how long it takes for the asteroid to complete one orbit.</p>
  <p><strong>25. Perihelion Distance:</strong> Indicates how close the asteroid gets to the Sun during its orbit.</p>
  <p><strong>26. Perihelion Arg:</strong> A measure related to the direction of the asteroid's orbit.</p>
  <p><strong>27. Aphelion Dist:</strong> Specifies how far the asteroid is from the Sun during its orbit.</p>
  <p><strong>28. Perihelion Time:</strong> The time when the asteroid is closest to the Sun.</p>
  <p><strong>29. Mean Anomaly:</strong> A measure of where the asteroid is in its orbit.</p>
  <p><strong>30. Mean Motion:</strong> Provides information about how the asteroid moves in its orbit.</p>
  <p><strong>31. Equinox:</strong> Specifies the reference point for the orbital information.</p>
  <p><strong>32. Hazardous:</strong> Target variable indicating whether the asteroid is considered hazardous to Earth; 1 for hazardous, 0 for not hazardous.</p>
</div>

<style>
  .column-definitions {
    font-family: Arial, sans-serif;
    padding: 20px;
    border: 1px solid #ccc;
    background-color: #f7f7f7;
  }
</style>

